### ISSUE TITLE
Team member question

### ISSUE THREAD

**Issue by miguelgfierro** [JPBP22/engine#10]
I see contributions from @HenningGC @JPBP22 and @AEscF, however, where are the github of the others and where are their contributions?

**Comment by JPBP22** [comment]
Hello Professor,

As I stated in my e-mail previously. We worked remotely all on JPs computer while at his house and the work was pushed from his computer and account. We now realise this was a mistake as it could mess with the workflow and are not gonna do that again. Either way, as my teammates can attest, we have all worked on this project together. E.g. As MLOps Engineer I am now working to deploy the application on azure and setup the CI/CD Integration.

**Comment by JPBP22** [comment]
Hello Professor, previously we all worked from my works station and pushed from here. We now realise this presents and issue but I can assure you we have all worked on this project in an equitable manner.
